CREATE DATABASE IF NOT EXISTS vacancies;
USE vacancies;

CREATE TABLE IF NOT EXISTS job_vacancies (
    CODIGO_VACANTE VARCHAR(50) PRIMARY KEY,
    TITULO_VACANTE TEXT,
    DESCRIPCION_VACANTE TEXT,
    NIVEL_ESTUDIOS VARCHAR(50),
    RANGO_SALARIAL VARCHAR(100),
    DEPARTAMENTO VARCHAR(100),
    MUNICIPIO VARCHAR(100),
    TIPO_CONTRATO VARCHAR(100),
    CANTIDAD_VACANTES INT,
    CARGO VARCHAR(200),
    FECHA_VENCIMIENTO DATETIME,
    SECTOR_ECONOMICO VARCHAR(200),
    TELETRABAJO BOOLEAN,
    DISCAPACIDAD BOOLEAN,
    MESES_EXPERIENCIA_CARGO INT,
    HIDROCARBUROS BOOLEAN,
    PLAZA_PRACTICA BOOLEAN,
    FECHA_PUBLICACION DATETIME,
    SALARIO_MIN DECIMAL(12,2),
    SALARIO_MAX DECIMAL(12,2),
    INDEX idx_departamento (DEPARTAMENTO),
    INDEX idx_fecha_publicacion (FECHA_PUBLICACION),
    INDEX idx_cargo (CARGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 